"""Step 3: smoke-test the shared base image on a real GPU.

Runs on: Modal, one L4 GPU, using the exact image tasks will use (pulled from Docker Hub).
Run from the project root:  uv run modal run scripts/s03_smoke_test.py
Writes: data/smoke_s03.jsonl, one result per checked row.

Checks, in order:
  1. versions   CUDA visible, torch 2.5.1, triton 3.1.0
  2. row 0      KernelBook's oracle (SumAggregatorNew) matches the reference python / pytorch code on the GPU
  3. sample     the same check on 20 random kept rows (fixed seed: reproducible)

The oracle check copies the reference's weights into the oracle module (load_state_dict),
because step 2 showed that rebuilding a module with the same seed does NOT reproduce
weights made from uninitialized memory. The grader (step 4) will do the same.
"""

import json
import random
from pathlib import Path

import modal

from kernel_env.config import BASE_IMAGE, DATA

SAMPLE_SIZE = 20        # rows checked beyond row 0; small enough to be cheap, wide enough to catch systemic failures
SAMPLE_SEED = 0         # fixed so re-runs always check the same rows (reproducible baseline)
# float32 addition is not associative: Triton and PyTorch fuse ops differently, so outputs
# diverge by a few ULPs even when both are correct. RTOL/ATOL define "close enough".
# Must match the grader's torch.allclose() exactly, or a kernel can pass smoke but fail training.
RTOL = 1e-3             # relative tolerance: |got - expected| <= atol + rtol * |expected|
ATOL = 1e-5             # absolute tolerance: floor for near-zero values where rtol collapses to 0
OUT = DATA / "smoke_s03.jsonl"   # one JSON result per row; inspect manually or diff across runs

app = modal.App("kernelbook-s03-smoke")
# The same image every task container uses, plus our kernel_env/ package added by Modal at
# run time. Needed because Modal starts each container by re-importing THIS script, and
# line `from kernel_env.config import ...` above must work there too. The Docker Hub
# image itself stays dependencies-only (option B); this only affects the smoke test.
image = modal.Image.from_registry(BASE_IMAGE).add_local_python_source("kernel_env")


# run inside the image on a GPU, so we can check that CUDA is visible and the GPU is usable.
@app.function(image=image, gpu="L4", timeout=300)
def check_versions() -> dict:
    from importlib.metadata import version

    import torch
    import triton
    # Report every pinned version, so a rebuilt image that drifted is caught here.
    return {"cuda": torch.cuda.is_available(), "gpu": torch.cuda.get_device_name(0),
            "torch": torch.__version__, "triton": triton.__version__,
            "numpy": version("numpy"), "mcp": version("mcp")}



# max_containers=1: all rows run one after another in a single L4 container. Each row takes
# seconds, while starting a container (image, torch import, Triton setup) takes tens of
# seconds, so one container is cheapest. Without it, .map() would start one GPU per row.
# timeout is per row; 600 s leaves room for the first row's one-time Triton compilation.
@app.function(image=image, gpu="L4", timeout=600, max_containers=1)
def check_oracle(row: dict) -> dict:
    """Check 2 (and 3): does KernelBook's own Triton answer match the PyTorch code it
    replaces, on a GPU, inside our image?

    Why: every task has a question (python_code, plain PyTorch) and an answer key
    (triton_code, Triton generated by Inductor). During RL the grader compares the
    MODEL's Triton answer against the question's output. Before trusting that comparison,
    we run it on an answer we know is right: if the answer key fails, the setup is broken
    (wrong torch version, wrong weights, wrong tolerances), not the answer.

    Steps:
      1. Load both code strings as modules, from real .py files (@triton.jit reads its
         kernel's source from the file it lives in; exec() of a string fails).
      2. Build both models on the GPU in eval mode: <Module> from the question,
         <Module>New from the answer key, with the args from get_init_inputs().
      3. Copy the reference's weights into the answer key's model by name, so both use
         identical weights (step 2 showed re-seeding doesn't guarantee that).
         strict=False records names that don't line up instead of crashing.
      4. Seed, then make one set of inputs with get_inputs(), moved to the GPU.
      5. Run both, each on its own clone of the inputs (a model may edit them in place).
      6. Compare: shapes first, then the largest gap (max_abs_diff), then
         allclose(rtol=1e-3, atol=1e-5), the grader's exact tolerances.
      7. Any error is caught and stored in the result; one bad row never stops the run.

    Reading a failure:
      error mentions torch._inductor        -> the torch 2.5.1 pin is wrong for this dataset
      missing_keys / unexpected_keys        -> weight names differ: the grader needs a mapping
      ok False with a large max_abs_diff    -> different numbers: bad row or tolerance too tight

    Example (row 0, SumAggregator, no weights):
      question:    return torch.sum(neighbor, dim=1)
      answer key:  one @triton.jit kernel adding the 4 slices along dim 1
      inputs:      one 4x4x4x4 tensor of random numbers in [0, 1)
      expected:    4x4x4 tensor from torch.sum
      got:         4x4x4 tensor from the Triton kernel
      result:      {"uuid": 0, "ok": True, "max_abs_diff": ~1e-7,
                    "missing_keys": [], "unexpected_keys": [], "error": None}
    """
    import importlib.util
    import tempfile
    import traceback
    import torch

    result = {
              "uuid": row["uuid"], "module_name": row["module_name"], "ok": False,
              "max_abs_diff": None, "missing_keys": [], "unexpected_keys": [], "error": None
             }

    def load(code: str, name: str):
        # From a real file, not exec(): @triton.jit reads the kernel's source from its file.
        path = Path(tempfile.mkdtemp()) / f"{name}.py"
        path.write_text(code)
        spec = importlib.util.spec_from_file_location(name, path)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        return module

    try:
        ref = load(row["python_code"], "reference")
        oracle = load(row["triton_code"], "oracle")
        args, kwargs = ref.get_init_inputs()                 # KernelBook format: [[args], {kwargs}]
        torch.manual_seed(0)
        ref_model = getattr(ref, row["module_name"])(*args, **kwargs).cuda().eval()
        oracle_model = getattr(oracle, row["module_name"] + "New")(*args, **kwargs).cuda().eval()

        """
        Copy weights so both models start from identical parameters: same seed isn't enough
        because the two constructors call different ops and draw a different number of random values.
        strict=False: log name mismatches in missing/unexpected_keys instead of raising.
        """
        keys = oracle_model.load_state_dict(ref_model.state_dict(), strict=False)
        result["missing_keys"], result["unexpected_keys"] = list(keys.missing_keys), list(keys.unexpected_keys)

        torch.manual_seed(1)
        inputs = [x.cuda() if torch.is_tensor(x) else x for x in ref.get_inputs()]
    
        with torch.no_grad():                                # clone: forward may edit inputs in place
            expected = ref_model(*[x.clone() if torch.is_tensor(x) else x for x in inputs])
            got = oracle_model(*[x.clone() if torch.is_tensor(x) else x for x in inputs])

        if got.shape != expected.shape:
            result["error"] = f"shape {tuple(got.shape)} != {tuple(expected.shape)}"
            return result
        
        result["max_abs_diff"] = (got.float() - expected.float()).abs().max().item()
        result["ok"] = torch.allclose(got, expected, rtol=RTOL, atol=ATOL)
    except Exception:
        result["error"] = traceback.format_exc(limit=2)[-300:]   # the end has the actual error
    return result


@app.local_entrypoint()
def main() -> None:
    print("1. versions:", check_versions.remote())

    rows = [json.loads(line) for line in open(DATA / "kept.jsonl")]
    row0 = next(r for r in rows if r["uuid"] == 0)
    sample = random.Random(SAMPLE_SEED).sample([r for r in rows if r["uuid"] != 0], SAMPLE_SIZE)

    # 2 + 3: row 0 first, then the sample, one after another in a single L4 container
    results = list(check_oracle.map([row0, *sample], return_exceptions=True))
    OUT.write_text("".join(json.dumps(r if isinstance(r, dict) else {"error": repr(r)}) + "\n"
                           for r in results))

    print(f"2-3. oracle vs reference ({len(results)} rows; row 0 first):")
    for r in results:
        if not isinstance(r, dict):
            print(f"   CRASH  {r!r}")
            continue
        flag = "PASS " if r["ok"] else "FAIL "
        keys = f" missing={len(r['missing_keys'])} unexpected={len(r['unexpected_keys'])}" \
            if r["missing_keys"] or r["unexpected_keys"] else ""
        err = f"  {r['error'].strip().splitlines()[-1]}" if r["error"] else ""
        print(f"   {flag} uuid {r['uuid']:>5} {r['module_name']:<28} diff={r['max_abs_diff']}{keys}{err}")
    passed = sum(isinstance(r, dict) and r["ok"] for r in results)
    print(f"\n{passed}/{len(results)} oracles match their reference -> {OUT}")
